### PR TITLE
Jan15 Updates

### PR DESCRIPTION
**Pull request by bobpaulin**

### CODE REVIEW

**Comment by visualsuccessinc** [comment]
Bob-

Calling meeting with no advance notice is a challenge.  Can we please
strive for reasonable notice?

For example, i am in cancun - its a challenge to plan out a git meeting
from my iphone.

-s

On Thursday, January 15, 2015, Bob Paulin <notifications@github.com> wrote:

> Merged #13 <https://github.com/cjug/cjug-meeting-intro/pull/13>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cjug/cjug-meeting-intro/pull/13#event-219416795>.
>


-- 
Sent from Gmail Mobile

**Comment by visualsuccessinc** [comment]
What's a git meeting?

**Comment by divideby0** [comment]
So we use a framework called reveal.js to create an intro deck at the beginning of meetings with speaker info, upcoming events, etc:

https://github.com/cjug/cjug-meeting-intro

Before an upcoming event, we simply go in and update the relevant info and present the intro deck via web browser at:

http://cjug.github.io/cjug-meeting-intro/#/

Since it’s all on Github, Bob can edit the material from his phone.

--
Build Smarter Software.

Cedric Hurst, Principal
Spantree Technology Group, LLC
1144 W Fulton Market, Suite 120, Chicago, IL
email: cedric@spantree.net | phone: 888.386.5501
web: http://www.spantree.net

On January 15, 2015 at 8:59:36 AM, visualsuccessinc (notifications@github.com) wrote:

What's a git meeting?

**Comment by mminella** [comment]
Sorry...the "What is a git meeting" was my comment.  I had just replied to the email.  I didn't understand the question about "Calling meeting with no advance notice is a challenge".  What meeting was called without advance notice?

**Comment by visualsuccessinc** [comment]
Apparently my mistake

Doing math, must be git agenda for tonite meering.

-s

On Thursday, January 15, 2015, Michael Minella <notifications@github.com>
wrote:

> Sorry...the "What is a git meeting" was my comment. I had just replied to
> the email. I didn't understand the question about "Calling meeting with no
> advance notice is a challenge". What meeting was called without advance
> notice?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cjug/cjug-meeting-intro/pull/13#issuecomment-70121857>
> .
>


-- 
Sent from Gmail Mobile

**Comment by visualsuccessinc** [comment]
Apparently my mistake

Doing math, must be git agenda for tonite cjug meeting.

-s

On Thursday, January 15, 2015, Bob Paulin <notifications@github.com> wrote:

> ------------------------------
> You can merge this Pull Request by running
>
>   git pull https://github.com/cjug/cjug-meeting-intro master
>
> Or view, comment on, or merge it at:
>
>   https://github.com/cjug/cjug-meeting-intro/pull/13
> Commit Summary
>
>    - Update cjug.md
>    - Update logistics.md
>    - Update speaker.md
>    - added liferay logo
>    - updated sponsor page.
>
> File Changes
>
>    - *A* images/liferay-logo.jpg
>    <https://github.com/cjug/cjug-meeting-intro/pull/13/files#diff-0> (0)
>    - *M* sections/cjug.md
>    <https://github.com/cjug/cjug-meeting-intro/pull/13/files#diff-1> (18)
>    - *M* sections/logistics.md
>    <https://github.com/cjug/cjug-meeting-intro/pull/13/files#diff-2> (4)
>    - *M* sections/speaker.md
>    <https://github.com/cjug/cjug-meeting-intro/pull/13/files#diff-3> (18)
>    - *M* sections/sponsors.md
>    <https://github.com/cjug/cjug-meeting-intro/pull/13/files#diff-4> (2)
>
> Patch Links:
>
>    - https://github.com/cjug/cjug-meeting-intro/pull/13.patch
>    - https://github.com/cjug/cjug-meeting-intro/pull/13.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cjug/cjug-meeting-intro/pull/13>.
>


-- 
Sent from Gmail Mobile

**Pull request merged**
